name: Setup JS Env
description: Configures the CI environment for a JS project, checks out the current branch, installs node, installs dependencies and caches them. Assumes running in an environment that supports bash.

inputs:
  aws-access-key:
    description: AWS access key
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  ref:
    description: Proxies the Githubs actions/checkout@v2 config. The default is the ref that trigged the containing workflow.
    required: false
    default: ''
  fetch-depth:
    description: Proxies the Githubs actions/checkout@v2 config.
    required: false
    default: 1
  submodules:
    description: Proxies to Githubs actions/checkout@v2 config.
    required: false
    default: false
  node-version:
    description: The version of node to install. It will automatically attempt to extract the node version from the engines field in package.json and that always takes precedence. Defaults to `lts/*` (latest LTS release).
    required: false
    default: lts/*
  package-manager:
    description: The package manager used to cache project dependencies. One of `npm || yarn || pnpm` . Only change this if you are using a custom install-command for these managers. Defaults to npm.
    required: false
    default: npm
  install-command:
    description: Overwrite the dependency install command. Defaults to `npm ci --ignore-scripts`.
    required: false
    default: npm ci --ignore-scripts

outputs:
  node-version:
    description: The node version the environment configured.
    value: ${{ steps.node-version.outputs.version || inputs.node-version }}

runs:
  using: composite
  steps:
    - uses: unfor19/install-aws-cli-action@v1.0.2
      name: install-aws-cli-action
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    - uses: actions/checkout@v2
      name: Checkout
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.submodules }}
    - run: echo "::set-output name=version::$(jq -r .engines.node package.json)"
      name: Get Node Version
      id: node-version
      shell: bash
    - uses: actions/setup-node@v2
      name: Setup Node
      with:
        node-version: ${{ steps.node-version.outputs.version || inputs.node-version }}
        cache: ${{ inputs.package-manager }}
    - run: aws codeartifact login --tool npm --repository fena --domain repo --domain-owner 578657107977
    - run: ${{ inputs.install-command }}
      name: Install Deps
      shell: bash

